---
title: "Species distribution atlas for the Estuary and Gulf of St. Lawrence"
author: David Beauchesne
lang: en
abstract:
fontfamily: fourier
linestretch: 1
fontsize: 10pt
lof: no
output:
pdf_document:
    highlight: kate
    toc: yes
    toc_depth: 3
    fig_caption: yes
    keep_tex: yes
    latex_engine: pdflatex
    number_section: yes
md_document:
    variant: markdown_strict
---

<!-- rmarkdown::render(input = './BioticAtlas/Code/01-SpeciesAtlas.Rmd', 'pdf_document') -->

<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
<!-- Setting up the pipeline
<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
```{r comment=">", echo = FALSE, eval = TRUE, include = FALSE}

# -=-=-=-=-=-=-=-=-=--=-=-=-=-=-=-=-=-=-
#              Libraries
# -=-=-=-=-=-=-=-=-=--=-=-=-=-=-=-=-=-=-
library(sf)
library(magrittr)
library(tidyverse)
library(raster)

# -=-=-=-=-=-=-=-=-=--=-=-=-=-=-=-=-=-=-
#             Biotic data
# -=-=-=-=-=-=-=-=-=--=-=-=-=-=-=-=-=-=-
# Biotic data
load('../../BioticData/SpeciesOccurrence/Data/SpeciesOccurrences.RData')
# load('./BioticData/SpeciesOccurrence/Data/SpeciesOccurrences.RData')

# -=-=-=-=-=-=-=-=-=--=-=-=-=-=-=-=-=-=-
#             Species list
# -=-=-=-=-=-=-=-=-=--=-=-=-=-=-=-=-=-=-
load('../../BioticData/SpeciesList/Data/SpeciesList.RData')
# load('./BioticData/SpeciesList/Data/SpeciesList.RData')

# Minimum record number accepted (subjective)
minRec <- 50

# Filter
sp <- sp %>%
      filter(Count >= minRec)

# Number of species
nSp <- nrow(sp)


# -=-=-=-=-=-=-=-=-=--=-=-=-=-=-=-=-=-=-
#        Predicted distributions
# -=-=-=-=-=-=-=-=-=--=-=-=-=-=-=-=-=-=-
load('../../BioticDistribution/RandomForest/Data/RandForest_Regression.RData')
load('../../BioticDistribution/RandomForest/Data/RandForest_Regression_Smooth.RData')
load('../../BioticDistribution/RandomForest/Data/RandForest_Classification.RData')
load('../../BioticDistribution/RandomForest/Data/RandForest_Classification_Smooth.RData')
# load('./BioticDistribution/RandomForest/Data/RandForest_Regression.RData')
# load('./BioticDistribution/RandomForest/Data/RandForest_Regression_Smooth.RData')
# load('./BioticDistribution/RandomForest/Data/RandForest_Classification.RData')
# load('./BioticDistribution/RandomForest/Data/RandForest_Classification_Smooth.RData')


# -=-=-=-=-=-=-=-=-=--=-=-=-=-=-=-=-=-=-
#              Study area
# -=-=-=-=-=-=-=-=-=--=-=-=-=-=-=-=-=-=-
load('../../eDriversGrids/Data/egslSimple.RData')
# load('./eDriversGrids/Data/egslSimple.RData')


# -=-=-=-=-=-=-=-=-=--=-=-=-=-=-=-=-=-=-
#            Color palette
# -=-=-=-=-=-=-=-=-=--=-=-=-=-=-=-=-=-=-
# colPal <- c("#c7cbce", "#96a3a3", "#687677", "#222d3d", "#25364a", "#c77f20",
#             "#e69831", "#e3af16", "#e4be29", "#f2ea8b")
# colPal <- c('#649DA7','#9FCED1','#CCBB96', '#E1BA6C','#B04D1A')
# colPal <- c('#2C3154','#2F4A73','#2B8F9C','#58B79D','#D3AA45')
# library(viridis)
# colPal <- viridis_pal()(10)
# rbPal <- colorRampPalette(c('#d7d7d7','#F2F4C8','#66BDBB','#294492','#883333'))
# rbPal <- colorRampPalette(c('#1FAFEB','#45E7D7','#81FEB9','#BAEE96','#F9B86B','#FD6E42','#FC111D'))
# rbPal <- colorRampPalette(c('#ffffff','#DBE1E1','#B8C9C6','#869E9B','#5A7475','#435259'))
# rbPal <- colorRampPalette(c('#2C3154','#2F4A73','#2B8F9C','#58B79D','#D3AA45'))
rbPal <- colorRampPalette(c('#e4ffff','#14808C','#085061','#692932','#fa6d6d'))

# -=-=-=-=-=-=-=-=-=--=-=-=-=-=-=-=-=-=-
#           Graphic layout
# -=-=-=-=-=-=-=-=-=--=-=-=-=-=-=-=-=-=-
mat <- matrix(c(0,1,1,6,2,2,3,3,4,4,5,5), ncol = 4, nrow = 3, byrow = T)
```



# Overview

This document is an atlas of species distribution models for the Estuary and
Gulf of St. Lawrence in Eastern Canada.

```{r echo = FALSE, fig.height = 10, fig.width = 10, fig.align = 'center'}
par(mar = c(0,0,0,0))
plot(st_geometry(egslSimple))
plot(st_geometry(biotic), pch = 20, cex = .1, col = '#5d5e5c', add = T)
```

\pagebreak


```{r echo = FALSE, results = 'asis', fig.height = 14, fig.width = 12, fig.align = 'center'}
# Loop through species
for(i in 1:1) {
  # Section title (taxa name)
  cat('\n')
  cat("#", paste(sp$species[i]), "\n")
  cat('\n\n')

  # -=-=-=-=-=-=-=-=-=--=-=-=-=-=-=-=-=-=-
  #     Species empirical occurrences
  # -=-=-=-=-=-=-=-=-=--=-=-=-=-=-=-=-=-=-
  # Identify species in biotic data
  uid <- biotic$species == sp$species[i]

  # Plot empirical data
  layout(mat)#, heights = c(1,.8,.8), widths = c(.8,1,1,.8))
  par(mar = c(1,1,1,1))

  # Study area
  plot(st_geometry(egslSimple))

  # Absences
  uid2 <- biotic$presence[uid] == 0
  plot(st_geometry(biotic[uid[uid2], ]), pch = 20, cex = .75, col = '#8a383888', add = T)

  # Presences
  uid2 <- biotic$presence[uid] == 1
  plot(st_geometry(biotic[uid[uid2], ]), pch = 20, cex = .75, col = '#4d81a788', add = T)


  # -=-=-=-=-=-=-=-=-=--=-=-=-=-=-=-=-=-=-
  #    Species predicted distribution
  # -=-=-=-=-=-=-=-=-=--=-=-=-=-=-=-=-=-=-
  # Regression
  par(mar = c(1,2.5,1,2.5))
  image(RF_regression[[i]], col = rbPal(256), zlim = c(0,1), axes = F,
        ylab = '', xlab = '', main = 'Random forest - Regression')

  # Smoothed regression
  image(RF_regression_smooth[[i]], col = rbPal(256), zlim = c(0,1), axes = F,
        ylab = '', xlab = '', main = 'Random forest - Regression - Smoothed')

  # Classification
  image(RF_classification[[i]], col = rbPal(256), zlim = c(0,1), axes = F,
        ylab = '', xlab = '', main = 'Random forest - Classification')

  # Smoothed regression
  image(RF_classification_smooth[[i]], col = rbPal(256), zlim = c(0,1), axes = F,
        ylab = '', xlab = '', main = 'Random forest - Classification - Smoothed')

  # -=-=-=-=-=-=-=-=-=--=-=-=-=-=-=-=-=-=-
  #              Legend
  # -=-=-=-=-=-=-=-=-=--=-=-=-=-=-=-=-=-=-
  graphicsutils::plot0()
  points(x = -1, y = .75, pch = 20, cex = 2, col = '#4d81a7')
  points(x = -1, y = .6, pch = 20, cex = 2, col = '#8a3838')
  text(x = -.75, y = .75, 'Presence', cex  = 1.25, adj = c(0,.5), font = 2)
  text(x = -.75, y = .6, 'Absence*', cex  = 1.25, adj = c(0,.5), font = 2)
  text(x = -.75, y = .45, '*Sometimes includes\npseudo absences', cex = .9, adj = c(0,.5))

  # Page break
  cat('\n\n\\pagebreak\n')
}
```
